# VERSION 1.0 (apache-superset)
# AUTHOR: Abhishek Sharma<abhioncbr@yahoo.com>
# DESCRIPTION: apache superset docker-compose.yml
# Modified/revamped version of the https://github.com/apache/incubator-superset/blob/master/contrib/docker/docker-compose.yml

version: '3'
services:
  redis:
    image: redis:3.2
    container_name: 'redis'
    restart: always
    ports:
      - 6379:6379
    volumes:
      - redis:/data
  mysql:
    image: mysql:5.7
    container_name: 'mysql'
    restart: always
    environment:
      MYSQL_USER: sa
      MYSQL_PASSWORD: password
      MYSQL_DATABASE: superset
      MYSQL_ROOT_PASSWORD: password
    ports:
      - 3306:3306
    volumes:
      - mysql:/var/lib/mysql
  superset:
    image: abhioncbr/docker-superset:0.32.0rc2
    container_name: 'superset'
    restart: always
    environment:
      MYSQL_USER: sa
      MYSQL_PASS: password
      MYSQL_DATABASE: superset
      MYSQL_HOST: mysql
      MYSQL_PORT: 3306
      REDIS_HOST: redis
      REDIS_PORT: 6379
      SUPERSET_ENV: local
      GOOGLE_APPLICATION_CREDENTIALS: ${GOOGLE_APPLICATION_CREDENTIALS}
    ports:
      - 8088:8088
      - 5555:5555
    depends_on:
      - mysql
      - redis
    volumes:
      - ../config/:/home/superset/config/
volumes:
  mysql:
    external: false
  redis:
    external: false