version: '3'

services:

  scraper:
    image: trans_met/scraper
    container_name: "scraper"
    build: 
      context: .
      dockerfile: Dockerfile
    environment:
      - MONGO_HOST=mongo
      - MONGO_PORT=27017
      - MONGO_DB=ba
      - MONGO_COLLECTION=points
    env_file:
      - .env  
    depends_on:
      - mongo
  
  mongo:
    image: mongo:4
    container_name: "mongo"
    ports:
      - "27017:27017"
    volumes:
      - transMet_data:/data/db

volumes:
  transMet_data:
    external: true